### ISSUE TITLE
Add support for currently unsupported message options

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#101]
According to the [Server Reference](https://developer.android.com/google/gcm/server-ref.html#table1), there are options we do not currently support:

- ~~`delivery_receipt_requested`~~
- `restricted_package_name`

**Comment by ToothlessGear** [comment]
`restricted_package_name` should be easy to add, however `delivery_receipt_requested` is for XMPP as per Server Reference, so we'll have to hold back on this one.

**Comment by hypesystem** [comment]
Ah! I missed that. You are right.
