### ISSUE TITLE
Find a better default name for the `result` returned from send.

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#104]
This may look like a small issue, but suggesting code like this causes problems with readability:

```js
sender.send(message, registrationIds, function(error, result) {

});
```

Why? Well, if we want to iterate over the internal results, we get this:

```js
result.results.forEach(function(result) {
  //yep, that's right. two `result`s.
});
```

You may suggest simply changing the inner variable in the `forEach` to something else, but that won't change the fact that the most obvious name for an entry in a list called `results` is `result`.

What we *can* change, however, is the suggested name of the `result`-object returned from ´Sender#send`.

---

Alternatively, the result could be wrapped in some abstraction that would make it more accessible.

**Comment by SarasArya** [comment]
I think message_id would be fine. In case of success. In case of failure probably just a message

**Comment by eladnava** [comment]
@hypesystem maybe rename the `sender.send` callback param to:

* `info`?
* `response`?
* `status`?

Or, maybe we can rename the internal `results` object to `messages`? Or `devices`?

**Comment by hypesystem** [comment]
I like `response` :smile:

**Comment by eladnava** [comment]
@hypesystem Sounds good -- so the modification should only be in the documentation, correct? And any tests as well.

**Comment by hypesystem** [comment]
Yes, that is correct.
