### ISSUE TITLE
Support in UTF-8 ? Hebrew Characters? Emoticons?

### ISSUE THREAD

**Issue by shaharlinial** [ToothlessGear/node-gcm#112]
I can't get Hebrew characters sent with this package.

Is this an issue? is this a known issue?

**Comment by hypesystem** [comment]
It is not a known issue, but also not something I have tested.

I find it likely that it has more to do with serialization/deserialization than this actual library. Do you have some example code you can share? (In fact, both server-side and client-side would be interesting in this case.)

**Comment by shaharlinial** [comment]
I can confirm that node-gcm + request support Hebrew characters without any special modifications.
The issue was caused by other library that didn't know how to handle payload in hebrew without encodeURIComponent, however node-gcm and request doesn't need encodeURIComponent to deliver a message in Hebrew.

Very well written @hypesystem .

**Comment by hypesystem** [comment]
Great! Thank you for your time :) I am glad you got your issue resolved.
