### ISSUE TITLE
error: InvalidRegistration

### ISSUE THREAD

**Issue by kvdmolen** [ToothlessGear/node-gcm#113]
Hi,

I don't understand the RegistrationID: GCM requires a `Sender ID` which is the sender of the message, AND the receiver ID.

But in the example-code I only see:

```
// Add the registration IDs of the devices you want to send to
var registrationIds = [];
registrationIds.push('regId1');
registrationIds.push('regId2');
```

So that is the receiver. How can I set both the `Sender ID` and `Receiver ID`?

**Comment by hypesystem** [comment]
Can you refer to where the documentation mentions this sender ID?

You may be talking about the API key, which is given to the `Sender` on creation:

```js
var sender = new gcm.Sender('YOUR_API_KEY_HERE');
```

**Comment by kvdmolen** [comment]
Hmm, I think you're right, GCM knows who the sender is via the API key..
Let me get back on this, thanks!

**Comment by woojoo666** [comment]
Anybody know how I would find the registration ID for an android app? I'm following the Android quickstart tutorial [here](https://developers.google.com/cloud-messaging/android/start)

**Comment by woojoo666** [comment]
nevermind, its from the getRegistrationId function

**Comment by hypesystem** [comment]
For reference: When registering an app with GCM (https://developers.google.com/mobile/add) you get a Sender ID and an API Key. The Sender ID is used *in the app* to generate registration IDs. The API key is used in the server (which is what node-gcm provides).

Closing this issue.
