### ISSUE TITLE
Not working getting the issue TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by mssrandhir** [ToothlessGear/node-gcm#119]
Am using `node-gcm` in my sails js application to send push notifications to android devices.But when am calling the method:

 // Set up the sender with you API key 
var sender = new gcm.Sender('my-api-key');
var registrationIds = [];
//push the device id's to array
	for (var i = 0; i < users.length; i++) {
		registrationIds.push(users[i].Device_Id);
	}
	// ... trying only once 
	sender.sendNoRetry(message, registrationIds, function(err, result) {
	if (err) {
						console.error(err);
					} else {
						console.log(result);
					}
				});

Am getting the error TypeError: Object.keys called on non-object
![oie_gtqcqamuniva](https://cloud.githubusercontent.com/assets/6560308/7344961/49230342-ecee-11e4-8fa1-b67d5abfe873.png)

**Comment by hypesystem** [comment]
Did you fix your issue? How?

**Comment by mdjaman** [comment]
Ping @mssrandhir did you fix it? If so can you write how it could help folks like me
