### ISSUE TITLE
GCM send link has been changed

### ISSUE THREAD

**Issue by eliranswisa** [ToothlessGear/node-gcm#128]
Hi,

I am getting error 401 every time with a correct API key.
It looks like the link used to send a request is wrong.
Current link is https://android.googleapis.com/gcm/send when it should send to  
https://gcm-http.googleapis.com/gcm/send

Thanks.

**Comment by eliranswisa** [comment]
That's not the issue, sorry.

**Comment by hypesystem** [comment]
I hope you figure out what your problem is :)

**Comment by mashaly100200** [comment]
i think it's api key problem or not enable google cloud messages in google cpnsole for your application

**Comment by eladnava** [comment]
@mashaly100200 That actually makes a lot of sense. 401 is definitely authentication-related.
