### ISSUE TITLE
Use `to` for single registration ids/device keys/etc

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#134]
According to the new and fancy [GCM specs](https://developers.google.com/cloud-messaging/server-ref#downstream), the field `to` may hold a single registration id or a single notification key. This should be used when only a single registration id is sent.

**Comment by Deminetix** [comment]
Does this plugin support topics via the to field?

**Comment by hypesystem** [comment]
We do not, currently, use the `to` field at all.

Can you give me some more detail on how you would normally support topics via the `to` field? I couldn't immediately find anything when I looked at the specs I linked above.

**Comment by Deminetix** [comment]
The `to` field is used for multiple purposes in the new spec

Topic Messaging: https://developers.google.com/cloud-messaging/topic-messaging
Group Messaging: https://developers.google.com/cloud-messaging/notifications

You can pass in a topic: `/topic/foo`,  a groupId (which is an alias for multiple devices), or just the deviceId

**Comment by hypesystem** [comment]
With 0.11 (not released yet) this will be possible by sending a message like so:

```js
sender.send(message, "/topic/foo", function(error, result) {
    if(error) return console.error("Error", error);
    //...
});
```

That is exactly what this issue tracks: when it is closed, the feature will be in the master branch :)

**Comment by hypesystem** [comment]
These are great details and should probably be documented somewhere... I will look into that :)

**Comment by hypesystem** [comment]
@Deminetix version 0.11 has now been released. Let me know if all that group and topic messaging works --- I haven't tried that part of it yet, myself.
