### ISSUE TITLE
Add support for Priority option

### ISSUE THREAD

**Issue by Faleij** [ToothlessGear/node-gcm#136]

**Comment by hypesystem** [comment]
Some more details about the option and a link to the relevant documentation would be very nice :)

**Comment by Faleij** [comment]
Thought the devs would already know about the official docs GCM, nevertheless here's the link: https://developers.google.com/cloud-messaging/server-ref See table 1. Options. priority.

**Comment by hypesystem** [comment]
It is always hard to have a discussion without a starting point ;)

This looks like a fairly small change. It just needs to be added to the message and sender as any normal argument.
