### ISSUE TITLE
[Error: SELF_SIGNED_CERT_IN_CHAIN]

### ISSUE THREAD

**Issue by pranaydutta89** [ToothlessGear/node-gcm#143]
I am using this plugin from my companies network ,which is behind proxy and getting error as [Error: SELF_SIGNED_CERT_IN_CHAIN] is there any way to disable the ssl ??

**Comment by hypesystem** [comment]
We do not have any option to do this at the moment, I'm sorry. It is very much the kind of thing that could be added, though.

**Comment by pranaydutta89** [comment]
do we have any hack as an alternative , i need this thing working for me

**Comment by hypesystem** [comment]
You can probably find a way to make the internal `request` object be insecure.

Here we set the options for it inside the `Sender`: https://github.com/ToothlessGear/node-gcm/blob/master/lib/sender.js#L44-L53

Here is the library with documentation: https://github.com/request/request

**Comment by pranaydutta89** [comment]
thanks a ton will try it ,but i think this feature should be included in node-gcm

**Comment by eladnava** [comment]
@pranaydutta89 It is now possible to [set custom `request` options](https://github.com/ToothlessGear/node-gcm#custom-gcm-request-options) such as `strictSSL: false`.
