### ISSUE TITLE
The readme's link to the notification payload reference is dead

### ISSUE THREAD

**Issue by bastienleonard** [ToothlessGear/node-gcm#149]
I get a 404 now: https://developers.google.com/cloud-messaging/server-ref#table1

Does anyone know what's the new link?

The old one is still available in Google's cache: http://webcache.googleusercontent.com/search?sourceid=chrome-psyapi2&ion=1&ie=UTF-8&q=cache%3Ahttps%3A%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fserver-ref%23table1&oq=cache%3Ahttps%3A%2F%2Fdevelopers.google.com%2Fcloud-messaging%2Fserver-ref%23table1&aqs=chrome..69i57.1422j0j4&bav=on.2,or.r_cp.&biw=2558&bih=1223&dpr=1&ech=1&psi=4MDeVfzaIYf6ywOk8YWgAw.1440661731344.3&ei=4MDeVfzaIYf6ywOk8YWgAw&emsg=NCSR&noj=1

**Comment by hypesystem** [comment]
https://developers.google.com/cloud-messaging/http-server-ref

This needs a PR :)

**Comment by hypesystem** [comment]
(they changed it with the announcement on Android M)

**Comment by bastienleonard** [comment]
Seems like Google now redirects the old link to the new one, so I'm closing this.

**Comment by hypesystem** [comment]
Silly Google ...
