### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by tonespy** [ToothlessGear/node-gcm#151]
I'm getting a 401 error. I am kind of confused with the Naming Conventions though. Expecially the 

var regIds = ['YOUR_REG_ID_HERE']; and
var sender = new gcm.Sender('YOUR_API_KEY_HERE');

This is what I think. `API_KEY` in sender is the 10digit `Project number` given to you by google.
and `regIds` is/are the Alpha-Numeric long String called `Server API Key`. I don't know what to debug since it's given 401 which means `Unauthorized Access`. But, this is what I'm doing I'm setting it up first on my sails/node app, but haven't set the mobile app to receive notification. But, that shouldn't return `401`. Any help would be appreciated. Thanks

**Comment by hypesystem** [comment]
You have it wonky:

- the API_KEY is the `Server API Key` (Alpha-Numeric string)
- the reg ids are created *on the device*, see [Obtain a registration token](https://developers.google.com/cloud-messaging/android/client#sample-register) in the documentation.

**Comment by tonespy** [comment]
@hypesystem If I have to obtain regIds from the device, wouldn't that be another problem? Cause, then I've to get IDs of every device I install my app before I can send them PUSH?

**Comment by hypesystem** [comment]
You *have* to get registration ids of every device you install your app on. That is how GCM works.

**Comment by tonespy** [comment]
Yeah. Just thought it through too. Thanks.

**Comment by SanjanaTailor** [comment]
How to get Registration id for phonegap-plugin from cordova

**Comment by eladnava** [comment]
Hi @SanjanaTailor,
Please consult StackOverflow or the phonegap-plugin-push documentation, your question is out of the scope of this project.
