### ISSUE TITLE
when i run it 400 error found

### ISSUE THREAD

**Issue by vishaloban** [ToothlessGear/node-gcm#157]
when i run it out put 400 error
![screenshot from 2015-09-09 18 19 38](https://cloud.githubusercontent.com/assets/6008292/9762176/691c7002-571f-11e5-855e-38ce611940bb.png)

**Comment by hypesystem** [comment]
The HTTP error 400 means that your request was malformed. Please share your code: how did you use node-gcm?

**Comment by eladnava** [comment]
@hypesystem @vishaloban Can we close this? No response for 2+ months.

**Comment by hypesystem** [comment]
Yeah :)
