### ISSUE TITLE
Depricated registration id

### ISSUE THREAD

**Issue by minal2709** [ToothlessGear/node-gcm#160]
Hey,

I see GCM has deprecated the registration ids. It uses tokens instead. This lib requires an update?

**Comment by hypesystem** [comment]
I am not sure I quite follow. According to the [server ref](https://developers.google.com/cloud-messaging/http-server-ref) Notification Keys are deprecated, but the registration_ids field is not. We support all of the available key types at the moment (topics, registration ids, notification keys).

**Comment by eladnava** [comment]
Google decided to rename the registration **IDs** in their documentation to registration **tokens**, which actually makes a lot more sense. However, they did leave the `registration_ids` HTTP GCM endpoint intact:
https://developers.google.com/cloud-messaging/http-server-ref

> registration_ids (String array) - This parameter specifies a list of devices (registration tokens, or IDs) receiving a multicast message. It must contain at least 1 and at most 1000 registration tokens.

If you wanted, you could update the docs and rename the IDs to tokens, but that's not really that important.

**Comment by hypesystem** [comment]
I think updating the docs would be great. There is the one issue of the named registrationIds argument we use. There should probably be an alias: registrationTokens.

**Comment by eladnava** [comment]
Good point. Here's what I'm planning to do:

* Update the docs, replacing the `registration IDs` terminology with `registration tokens`, as per the updated GCM docs
* Create an alias for `registrationTokens`, to maintain backward compatibility (by adding the alias to the `validKeys` array in [sender.js#L29](https://github.com/ToothlessGear/node-gcm/blob/master/lib/sender.js#L29))
* Update the docs to promote use of the `registrationTokens` parameter

What do you think?

**Comment by hypesystem** [comment]
:+1:

**Comment by eladnava** [comment]
@hypesystem Done. :)

**Comment by eladnava** [comment]
@hypesystem this can be closed.
