### ISSUE TITLE
TypeError: message.toJson is not a function

### ISSUE THREAD

**Issue by chunling89** [ToothlessGear/node-gcm#161]
Hi, found that the error occur when try to send notification.

sender.send(message, { registrationIds: registrationIds }, function (err, result) {
  if(err) console.error(err);
  else    console.log(result);
});

**Comment by hypesystem** [comment]
What are the contents of your `message`? How do you create the message?

**Comment by chunling89** [comment]
Found that is the message created not correctly. Thanks for your advice.
