### ISSUE TITLE
New GCM endpoint hostname

### ISSUE THREAD

**Issue by eladnava** [ToothlessGear/node-gcm#162]
Google decided to change its GCM HTTP endpoint to `https://gcm-http.googleapis.com/gcm/send`, instead of `https://android.googleapis.com/gcm/send`, likely because GCM is no longer Android-only.

https://developers.google.com/cloud-messaging/downstream

The parameters remain the same, just the hostname has changed.

Would you like me to update it in the `constants.js` file via a PR?

**Comment by hypesystem** [comment]
That would be great :-)

**Comment by psirenny** [comment]
@eladnava could the change to the endpoint be responsible for the recent **mismatch sender id** errors I've been receiving? If not I'll continue to explore what may be wrong with my api key.

**Comment by eladnava** [comment]
@psirenny I don't think it's related. I believe that `MismatchSenderId` means that you are trying to send push notifications using a `GCM Server API Key` that is linked to a different `SENDER_ID` than was used to generate some of your registration IDs on the client-side. 

People report that they get this error when trying to send push notifications to old [`C2DM` registration IDs](http://stackoverflow.com/a/11313861/1123355).

**Comment by hypesystem** [comment]
@psirenny the old endpoint still works but is deprecated, so this is *not* the cause of any errors :-)

**Comment by psirenny** [comment]
Thanks guys, you were right. My development and production project numbers got crossed.
