### ISSUE TITLE
iOS Support (update the docs)

### ISSUE THREAD

**Issue by eladnava** [ToothlessGear/node-gcm#166]
I think we should update the docs and repository description, as `node-gcm` does support iOS notifications via GCM, but the description is misleading, as it only mentions Android.

Repo description:

> A NodeJS wrapper library port to send data to Android devices via Google Cloud Messaging https://github.com/ToothlessGear/node-gcm

README.md:

> node-gcm is a Node.JS library for Google Cloud Messaging for Android, which replaces Cloud 2 Device Messaging (C2DM).

Also, not sure that the C2DM part is relevant anymore. Can I submit a pull request to modify the docs as follows?

> node-gcm is a Node.JS library for Google Cloud Messaging.

Anything else we'd like to add in the main description?

**Comment by hypesystem** [comment]
I think that would be a fine PR. Unfortunately only @ToothlessGear has access to the description of the library at the moment, so we'd need him to update it :-)

**Comment by eladnava** [comment]
Excellent, created a PR - #168 @hypesystem
