### ISSUE TITLE
error: 'InvalidRegistration' }

### ISSUE THREAD

**Issue by omaisali** [ToothlessGear/node-gcm#171]
I checked again and again, registration id is correct.  Why i am getting this. I am using node-gcm

{ multicast_id: 5492428094164707000,
  success: 0,
  failure: 1,
  canonical_ids: 0,
  results: [ { error: 'InvalidRegistration' } ] }
{ message_id: 5286640476742132000 }

**Comment by eladnava** [comment]
@omaisali can you please post the solution for others, if they encounter the same error?

**Comment by omaisali** [comment]
@eladnava  i was using ocr to get registration and thn i was putting it to server. Registration id was wrong as ocr adds some characters in it.
