### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by jhova-** [ToothlessGear/node-gcm#172]
You should change registrationTokens to registrationIds, would of saved me days of trouble if the documentacion was correct. Anywho pretty nice wrapper. Kudos.

**Comment by eladnava** [comment]
@hypesystem is the NPM package not up to date? That would probably have led to the confusion since it doesn't have the `registrationTokens` alias yet.

**Comment by hypesystem** [comment]
The NPM page is only updated when a new version is released. I haven't gotten around to releasing a new version yet, but we definitely should :-)

This issue has been solved.
