### ISSUE TITLE
'Invalid recipient key(s) registrationTokens (valid keys: registrationIds, topic, notificationKey)' Regardless

### ISSUE THREAD

**Issue by AlexCatch** [ToothlessGear/node-gcm#174]
Every time without fail I am getting this error when using an IOS registration ID.
It works when making a call directly to the GCM endpoint but the wrapper always returns 'invalid recipient  key' even when I directly copy the API key and reg ID from Postman.

**Comment by eladnava** [comment]
Please use `registrationIds` as the parameter name. `registrationTokens` is an alias we recently introduced -- unfortunately, the npm package has not been updated to support it yet. @hypesystem

**Comment by AlexCatch** [comment]
Thanks!
