### ISSUE TITLE
Not working from aws instance. Please help?

### ISSUE THREAD

**Issue by sunojvijayan** [ToothlessGear/node-gcm#175]
I have everything working from my laptop. Great job by the way. But when I try running the same code from an aws instance it's showing that it's a success but I am not getting any message. Do I have to open any additional port. Please help.

**Comment by eladnava** [comment]
All you need is outgoing port 443 (as we connect via GCM's HTTPS connection server).

However, it's possible that there's something else going on -- maybe your server doesn't trust the remote certificate because of missing or outdated CA certificates.

Are you sure that you aren't getting back an error in the `sender.send()` callback?

**Comment by hypesystem** [comment]
Please share your code so we can see if there are any hidden issues with it, @sunojvijayan :-)

We have node-gcm running in AWS and it works fine for us :)

**Comment by sunojvijayan** [comment]
My bad. Now its working. Sorry.

**Comment by eladnava** [comment]
@sunojvijayan can you tell us how you resolved the issue?

**Comment by sunojvijayan** [comment]
I am Sorry I am not sure what happened. But initially i ran the server using node command and it was not working. But after some time i ran it using forever and everything was working. Now even if I use node to run it it works.

**Comment by sunojvijayan** [comment]
I am facing another issue though. Not sure if its supposed to work like this, thats why I am not raising another issue request. But when I push and if the phone has been idle for sometime it wont show notification until I unlock the phone. Is this normal?

**Comment by sunojvijayan** [comment]
Sorry again. I got that too made delayWhileIdle: false and that works too. Thank you all for your help. Much appreciated.
