### ISSUE TITLE
Many NotRegistered error status

### ISSUE THREAD

**Issue by alexislg2** [ToothlessGear/node-gcm#176]
Hey,
I'm using your package with the Cordova Push plugin https://github.com/phonegap/phonegap-plugin-push

It works great. But after few days/weeks, my users start not receiving notifications. And when I look at the logs I receive NotRegistered errors with theses users.

When app sends a new regId I save it in my database (overwriting the previous one) and do the same when I receive a canonical_id. What am I doing wrong?

**Comment by eladnava** [comment]
@alexislg2 you are receiving NotRegistered because:

* a user uninstalled your app and the registration ID is no longer valid
* a user updated your app (via Google Play) and the registration ID is no longer valid (you must request a new registration ID after updating the app)
* your app does not have a broadcast receiver configured to receive com.google.android.c2dm.intent.RECEIVE intents
* you misconfigured your AndroidManifest.xml with the required permissions / receivers / services for GCM

Is it possible that you released updates to the app recently and that you don't re-register after updating?

**Comment by alexislg2** [comment]
Hey
thanks for your quick answer. 

* I know some of the users who have this issue. I know for sure that they did not remove the app.
* Yes I did some APK update through Google Play store (beta distibution) but the first thing that the app does is to register on GCM, whatever it's an update or a normal start
* According to the plugin developers`, the plugin has a service com.adobe.phonegap.push.PushInstanceIDListenerService that will listen for any changes on the registration ID and throw a new registration event.`
* If there was a problem with the androidManifest.xml I think users would never receive any notifications. They receive it but after some days/weeks, the don't anymore

Thanks

**Comment by eladnava** [comment]
@alexislg2 are you registering every time the app is opened? That's very bad and could be the reason you are getting this error. You should not be registering unless the app is fresh-installed or updated, or the IDListenerService invokes the registration service for some other reason.

**Comment by alexislg2** [comment]
Oh oh that's interesting. Actually this is the way the Phonegap/cordova Pushplugin is coded. I will tell the developers about that. Do you have a link to the documentation that says we should register only after APK updates?

Thanks

**Comment by eladnava** [comment]
> In Google's official GCM Client Demo App they register to GCM only when a new version of the application is installed on the device. Therefore I assume that's the best practice.

Check out [this StackOverflow question](http://stackoverflow.com/questions/20910803/register-a-device-on-gcm-every-time-the-app-start-is-the-right-approach) which addresses this issue in regards to Cordova/PhoneGap.

**Comment by alexislg2** [comment]
OK according to the SO post, it does not seem to be so bad to register at every start, just a waste of time and data I think.

**Comment by eladnava** [comment]
@alexislg2 I recall having a similar issue where devices would not receive push notifications and I was able to solve it by not re-registering every time the app is restarted. I'd recommend avoiding it if you can, as it doesn't adhere to the GCM registration guidelines:

> 1. The client app obtains a registration token using the Instance ID API. The call to this API must have the authorized entity set to your app server's sender ID, and the scope set to the appropriate value for GCM (depending on your platform).
2. The client app passes the registration token to the app server.
3. The app server saves the registration token and acknowledges to the client app that the process completed successfully.

> If the app server fails to complete its part of the registration handshake, the client app should retry sending registration token to the server or delete the registration token.

https://developers.google.com/cloud-messaging/registration

**Comment by hypesystem** [comment]
@alexislg2 what is the status on this? Have you resolved your issue?

Either way, it seems it is not a `node-gcm` issue so I am going to close the issue on here :smile: let me know if this assumption is wrong
