### ISSUE TITLE
Documentation of allowed options

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#178]
We should document somewhere the options that can be given to the sender on creation https://github.com/ToothlessGear/node-gcm/blob/master/lib/sender.js#L5

**Comment by eladnava** [comment]
@hypesystem Am I right that these are the currently-available options?

```
    if (this.options && this.options.proxy) {
        post_options.proxy = this.options.proxy;
    }

    if (this.options && this.options.maxSockets) {
        post_options.maxSockets = this.options.maxSockets;
    }

    var timeout = Constants.SOCKET_TIMEOUT;

    if (this.options && this.options.timeout) {
        timeout =  this.options.timeout;
    }

    post_options.timeout = timeout;
    
    if (this.options && typeof(this.options.strictSsl) == "boolean") {
        post_options.strictSSL = this.options.strictSsl;
    }
```

**Comment by hypesystem** [comment]
That is correct. See also #179, which discusses changing the behaviour to allow all options that are allowed in `request`. This would make the documentation much simpler: we would just refer to `request`'s documentation.

**Comment by eladnava** [comment]
@hypesystem Sounds good.

However, I think we need to change things a bit.

Right now, this is how you pass in configuration that influences the `request`:

```
var options = {
   proxy: 'http://myproxy.com',
   maxSockets: 100,
   tieout: 1000,
   strictSsl: false
};

// Set up the sender with you API key
var sender = new gcm.Sender('YOUR_API_KEY_HERE', options);
```

I think that we should pass in request-related params in a nested `request` object as follows:

```

var options = {
   request: {
      proxy: 'http://myproxy.com',
      maxSockets: 100,
      timeout: 1000,
      strictSsl: false
   }
};
```

What do you think?

**Comment by eladnava** [comment]
@hypesystem Excellent. Making it possible to override any request option is great. Let's see what the outcome of #179 is, and then we can figure out how to properly document the request params.

**Comment by eladnava** [comment]
@hypesystem Is [this](https://github.com/ToothlessGear/node-gcm#custom-gcm-request-options) enough documentation to close this issue?

**Comment by hypesystem** [comment]
Yes :)
