### ISSUE TITLE
Notification not coming in notification Area

### ISSUE THREAD

**Issue by purnendu9** [ToothlessGear/node-gcm#180]
Hi,
   I am trying to send messages. The messages are getting sent to the app. However the messages are not appearing in the notification area on top drawer.

The message object that gets sent is as below
{"collapseKey":"Updates Avaliable","priority":"high",
"contentAvailable":true,
"delayWhileIdle":true,
"restrictedPackageName":"XXXXXXXXXX",
"data":{
"key1":"message1","key2":"message2","eventName":"ar","message":"Test Is this coming","route":"XX"
},
"notification":{"title":"Hello from XX","icon":"mrkr1.png","body":"There is a New Appointment from My Best Guest"}
}

When it reaches the client i see this object received is as below

{"title":"Hello from XXX","message":"Test Is this coming","additionalData":{"e":"1","icon":"mrkr1.png","key1":"message1","key2":"message2","eventName":"ar","route":"XX","collapse_key":"XXXX","foreground":true}}

Researched at lot of places as to how to get the event appear in notification Area as well. Documentation does not say musch about it also

**Comment by hypesystem** [comment]
How does your code look on the client side? Are you using the regular Android SDK?

**Comment by purnendu9** [comment]
its phonegap sdk
exactly similar to https://github.com/ToothlessGear/node-gcm/issues/62

**Comment by hypesystem** [comment]
There have been issues with PhoneGap not supporting the `notifications` field previously. You should probably manually create the notification client-side based on the payload in `data`.

This is a PhoneGap issue so I am closing it.

**Comment by purnendu9** [comment]
You are right,
     Its not node gcm issue. However i debugged and was able to solve it. Just incase anyone stumbles here,
The Phonegap plugin needs the 3 notification fields. phonegap plugin reads the title and the icon from the "notification" object however the message needs to be set in the "data" object.

Thanks for clarifying

**Comment by eladnava** [comment]
@purnendu9 Thanks for clarifying, I'm sure it will help other people in the future!
