### ISSUE TITLE
Better errors on wrongly-typed recipients

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#186]
Following discussion in #185, I think we should handle invalidly typed keys in some meaningful way (eg. returning a sensical error).

**Comment by inampaki** [comment]
@hypesystem also it would be really nice if you guys list them all in the documentation.

**Comment by eladnava** [comment]
@inampaki They types of keys? `registrationTokens`, `topic`, etc?

**Comment by inampaki** [comment]
@eladnava I meant if returned error would be part of documentation will help the user of module in development to check on those messages in his / her code.

**Comment by eladnava** [comment]
@inampaki Currently we return a string as the value of the `err` callback param when sending messages.

Are you suggesting that we return an object with an error_code?

**Comment by inampaki** [comment]
@eladnava I am just saying that whatever error is returned. Please document in readme so that a developer who is using the API can check those in the code

**Comment by hypesystem** [comment]
@eladnava this has been discussed previously. The only problem is that it would be a breaking change, so it has been deferred until we are ready for 1.0

**Comment by eladnava** [comment]
@hypesystem I see, so we should hold off on that for now.

How would you like to return the invalidly typed keys?

**Comment by hypesystem** [comment]
I am open to suggestions :smile:

**Comment by eladnava** [comment]
@hypesystem how about the following `err` object:

```js
{
   "message": "Please provide `registrationTokens` as  an array of registration tokens"
}
```

Is there any other property you'd like added to the `err` object? A `code` maybe?

**Comment by hypesystem** [comment]
Seeing as this is a programmer error and they will probably read the message, I think this is fine :) I don't think a code would add anything in this case.

**Comment by hypesystem** [comment]
Maybe it could even be a proper `Error` object, so we get a stack trace :)

**Comment by eladnava** [comment]
@hypesystem I think an `Error` object is a great idea!

All we have to do is:

```js
new Error("Please provide 'registrationTokens' as an array.")
```

And return that as the `err` callback param.

I'll be making the following changes in `extractRecipient` located in [sender.js#L33]:(https://github.com/ToothlessGear/node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L33)

* Return an error if no recipient key was provided
* Return an error if `registrationIds` or `registrationTokens` is not an array
* Return an error if `topic` or `notificationKey` is not a string

And, add tests to `senderSpec.js` for invoking and testing these errors. Would you like to add anything before I begin?

**Comment by hypesystem** [comment]
Sounds good :+1:

**Comment by eladnava** [comment]
@hypesystem I'll also be listing them in the documentation.

**Comment by hypesystem** [comment]
:+1:
