### ISSUE TITLE
Sender.prototype.send() making bad assumption on recipient

### ISSUE THREAD

**Issue by alemonmk** [ToothlessGear/node-gcm#187]
It seems there's no documentation telling me how to supply recipient token when I need to send unicast message, so I have a look into lib/sender.js. From what I read, if I specify a single token (i.e. a string), it gets converted into a single-element array, and then call sendNoRetry().

In lib/sender.js/send()
```javascript
    if(typeof recipient == "string") {
        recipient = [recipient];
    }
    else if (!Array.isArray(recipient) && typeof recipient == "object") {
        // For topics, passing them to sendNoRetry() as if they were registration tokens
        // will put them in the "to" value of the JSON payload, which what we want
        var o = extractRecipient(recipient);

        if (o.err) {
            return callback(o.err);
        }
        else {
            recipient = o.recipient;
        }
    }
```
sendNoRetry() will put the single-element array into `registration_ids` which is [discouraged](https://developers.google.com/cloud-messaging/http-server-ref#table1):
> Use this(`registration_ids`) parameter only for multicast messaging, not for single recipients. 

PS. Is passing a `{ registrationTokens: 'a string token' }` sends a unicast job?

**Comment by eladnava** [comment]
Hey @alemonmk,
Sorry for the delayed response. You have a very good point there, regarding unicast messaging.

While sending a notification to one registration ID as a multicast message works perfectly fine, it would be better if we adhered to the GCM documentation, which specify that we should use the `to` parameter instead, if only sending to one recipient. @hypesystem, what do you think?

Regarding passing `{ registrationTokens: 'a string token' }` -- that won't work. That will crash the app / return an `err` to the send callback.

**Comment by hypesystem** [comment]
I agree that we should probably use the `to` field whenever possible :smile:

**Comment by eladnava** [comment]
@alemonmk PR #190 will now return an error if you try to pass in `{ registrationTokens: 'a string token' }`.

I will submit a PR soon that will change the behavior of providing a single registration ID (to use the `to` field instead of a single-element `registrationTokens` array).

**Comment by eladnava** [comment]
@hypesystem How about we add a to: recipient key as well? (In addition to registrationTokens and topic, for example).

**Comment by alemonmk** [comment]
Just wondering, wouldn't make this
```
    if(typeof recipient == "string") {
        recipient = [recipient];
    }
```
does nothing more straight forward?

**Comment by eladnava** [comment]
@alemonmk Thanks for pointing that out. Passing in a recipient as a string should also be treated as unicast messaging. I've added it to the PR as per your suggestion.

**Comment by alemonmk** [comment]
I found out that eladnava/node-gcm@8cdc4d9 probably would complicate things up in eladnava/node-gcm@703441d.
With this in mind, I suggest that having the parameter ```recipient``` required to be an object, which holds one of the following keys: ```to```, ```topic``` or ```registrationTokens``` (bring back ```notificationKey``` and ```registrationIds``` for the sake of compatibility). A breaking change, but I think it is cleaner.

**Comment by eladnava** [comment]
@alemonmk We should still make it possible to provide a string as the recipient object, for backward compatibility.

However, the [recipient types documentation](https://github.com/eladnava/node-gcm/commit/703441d) doesn't list them as they are not recommended (we'd prefer if people used the recipient keys instead). 

Regarding adding a `to` recipient key, waiting for @hypesystem's response:

> @hypesystem How about we add a to recipient key alias as well? (In addition to registrationTokens and topic, for example).

**Comment by alemonmk** [comment]
I see, thanks for clarification :)

**Comment by hypesystem** [comment]
@eladnava :+1: sounds great :smile: for some reason I actually thought we already supported a `to` recipient key, but it looks like we don't.

**Comment by eladnava** [comment]
@hypesystem @alemonmk  Waiting on #190 to be merged because it introduces a change in the way we check for recipient keys.

**Comment by eladnava** [comment]
@hypesystem Submitted the PR =)

**Comment by hypesystem** [comment]
And it's merged!
