### ISSUE TITLE
Return reason for 400

### ISSUE THREAD

**Issue by AdriVanHoudt** [ToothlessGear/node-gcm#198]
right now it returns just `400` which is not super helpful

**Comment by eladnava** [comment]
@AdriVanHoudt Good suggestion! What code are you using, by the way, that caused GCM to return a 400 Bad Request?

**Comment by AdriVanHoudt** [comment]
Trying to send to tokens that do not exist anymore, would love to catch this and basically ignore it while I still want to know when other stuff would fail for other reasons

**Comment by hypesystem** [comment]
There is already an issue on this: #71 -- please discuss how to improve errors in there.

**Comment by eladnava** [comment]
@AdriVanHoudt According to [the GCM error codes](https://developers.google.com/cloud-messaging/http-server-ref#error-codes), an invalid registration ID should return `200 + error:InvalidRegistration`, no?

**Comment by AdriVanHoudt** [comment]
@eladnava when I logged the 400 error I got `Invalid request (400): INVALID_REGISTRATION`

**Comment by eladnava** [comment]
@AdriVanHoudt Any chance you can post your code?

**Comment by hypesystem** [comment]
Seems I was too quick. It looks like a different issue :smile:

**Comment by AdriVanHoudt** [comment]
@eladnava not really :/ this is the message I am sending (with some other data)
I do know that some registration ids are probably not registered anymore so getting the error is fine
```js
Message {
  params:
   { data: undefined,
     notification:
      { title: 'this is my title',
        id: 121,
        image: 'http://foto.com/sonething.jpg',
        body: 'this is the body',
        tag: 121,
        style: 'inbox',
        summaryText: 'There are %n% new notifications',
        notId: 121 }
     } 
}
```

**Comment by eladnava** [comment]
@AdriVanHoudt How about your `recipient` object?

**Comment by AdriVanHoudt** [comment]
@eladnava ```js
{ multicast_id: 6173893188151682000,
  success: 0,
  failure: 1,
  canonical_ids: 0,
  results: [ { error: 'NotRegistered' } ] }
``` this?

**Comment by eladnava** [comment]
The  in the following snippet:

```js
// Now the sender can be used to send messages
sender.send(message, <!-- This -->, function (err, response) {
    if(err) console.error(err);
    else    console.log(response);
});```

@AdriVanHoudt

**Comment by hypesystem** [comment]
Can you try running your code with `DEBUG=node-gcm`? That should print the actual body returned from GCM.

According to the documentation a status code 400 means malformed JSON:

> Only applies for JSON requests. Indicates that the request could not be parsed as JSON, or it contained invalid fields (for instance, passing a string where a number was expected). The exact failure reason is described in the response and the problem should be addressed before the request can be retried.

([HTTP Connection Server Reference, Table 4](https://developers.google.com/cloud-messaging/http-server-ref#table4))

Are you sure the registration ids you pass are well-formed? (That they are not too long/short, that they are strings, etc.)

**Comment by AdriVanHoudt** [comment]
I run this 
`return sender.send(gcmMessage, { registrationIds: [session.registration_id] }, 10, (err, res) => {`
where `session.registration_id` is a registration token

the thing is on some it gives the error but when the token is actually registered the notification comes through and it is the exact same payload (apart from the reg id)

**Comment by eladnava** [comment]
@hypesystem Maybe the GCM server returns `400 Bad Request` if a single registration ID is specified with `to:`?

**Comment by hypesystem** [comment]
That would be very weird. Here's the documentation for `to`:

> This parameter specifies the recipient of a message.
>
> The value must be a registration token, notification key, or topic.

**Comment by AdriVanHoudt** [comment]
could it be that 
https://github.com/ToothlessGear/node-gcm/blob/master/lib/sender.js#L82-L87
should match 
https://github.com/ToothlessGear/node-gcm/blob/master/lib/sender.js#L90-L95
with the `if length === 1`?

**Comment by hypesystem** [comment]
Have you been able to reproduce while running with `DEBUG=node-gcm`?

**Comment by AdriVanHoudt** [comment]
tried that but printed nothing :/

**Comment by hypesystem** [comment]
What command are you executing to run your code?

**Comment by hypesystem** [comment]
My best be, currently, at what is going on: if the `to` field is set **and** the registration id given to `to` does not exist, maybe the "Topic message HTTP response" is given instead of the normal "Downstream Message HTTP message response". The topic HTTP response can be found here: https://developers.google.com/cloud-messaging/http-server-ref#table6

It seems entirely silly that the same endpoint returns data in an entirely different format depending on whether it thinks you *tried* to pass a topic or a registration_id, but this is my best bet.

Either way, the topic HTTP response is not something we are currently handling at all, and would probably require a new PR --- if nothing else, then for the cases where it should actually be returned (topic and maybe notification key).

**Comment by AdriVanHoudt** [comment]
I ran `DEBUG=node-gcm node server.js`

**Comment by hypesystem** [comment]
Odd! I will look into this more later and see if I can reproduce. Either way, I think this calls for some experimentation to figure out what is going on.

**Comment by eladnava** [comment]
@AdriVanHoudt Any slight chance that you can provide us with the bad registration ID that caused this weird behavior?

**Comment by AdriVanHoudt** [comment]
@eladnava would that be safe to post?

**Comment by eladnava** [comment]
@AdriVanHoudt I think so, since it's a bad registration ID anyway. If you want, replace some of the numbers with other numbers, and do the same for the letters.

**Comment by AdriVanHoudt** [comment]
this is one of the id's `3c54de9fd3d79bd52656f7a0c68d39dff1e3288ed9d998ef69f791103ff3f7b8`

**Comment by eladnava** [comment]
@AdriVanHoudt That looks like an APNS push token, not a GCM one. Could that be the reason for this strange behavior?

**Comment by AdriVanHoudt** [comment]
@eladnava ah yes that could be I currently do not distinct between the 2, well that solves it, thanks!

**Comment by hypesystem** [comment]
That is great news, because it means that the error message is actually correct :smile: No need for changes on this issue.

**Comment by hypesystem** [comment]
Thanks for reporting it, though @AdriVanHoudt, and good luck with your development :smile:

**Comment by AdriVanHoudt** [comment]
idd no need for changes although passing the 400 reason would still be handy
and thanks!
