### ISSUE TITLE
Linking to the npm package in README

### ISSUE THREAD

**Issue by eladnava** [ToothlessGear/node-gcm#201]
Hey @hypesystem,
Currently, we don't link to the node-gcm npm package in the README.md.

What do you say about adding a badge with the current latest version, like this:

![screen shot 2016-01-15 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/4394189/12354813/02051e14-bba1-11e5-9ded-0e5ebbb153a7.png)

It also links to the npm package.
http://badge.fury.io/

**Comment by hypesystem** [comment]
That sounds like a great idea! We should also probably emphasize that the `master` branch on here *may not* have been published yet

**Comment by eladnava** [comment]
@hypesystem Maybe a better idea is for us to always publish a patch version when something changes in the documentation?

**Comment by hypesystem** [comment]
I think we should be very careful with adding badges, so it doesn't get too bloated :smile:

The problem with automatically publishing a patch version on changes is twofold: (i) It might add functionality, and should be a minor version bump; and (ii) we would need to somehow sneak in CHANGELOG and package.json updates with every commit, then. I don't think it is a feasible solution.

**Comment by eladnava** [comment]
@hypesystem How about publishing only on documentation changes? So that the GitHub repo doesn't list a different (or new) API call than doesn't exist in the `npm` package yet.

I don't mind publishing as well after we merge pull requests with docs changes.

**Comment by hypesystem** [comment]
Sure, we could just publish patch bumps on every documentation change. Let's just do that :smile:

**Comment by eladnava** [comment]
@hypesystem Great!

Just `npm version patch && npm publish` after modifying the `CHANGELOG.md`, right?

**Comment by hypesystem** [comment]
You need to commit the patch version bump, too. But otherwise correct :smile:

**Comment by eladnava** [comment]
Great, so just to make sure: 

1. Run `npm version patch` on updated `ToothlessGear/master`
2. Modify the `CHANGELOG.md` adding the new version number and listing the changes
3. Run `git add . -A && git commit -m "0.13.2"`, the commit title the same as the patch version number
4. Run `npm publish && git push origin master`

**Comment by hypesystem** [comment]
Where `0.13.2` is replaced with the appropriate version number, yes. Current master is at 0.14.0.

Patch bumps when fixing issues, minor bumps when adding functionality.

Correct :smile:

**Comment by eladnava** [comment]
@hypesystem cool, thanks for clearing that up!
