### ISSUE TITLE
sender.send return "No RegistrationIds given!" with RegistrationIds given.....

### ISSUE THREAD

**Issue by ronyrun** [ToothlessGear/node-gcm#217]
Hello !

I have some trouble to make the sender work properly on my Ubuntu envt : 

```node
> process.arch
'arm'
> process.platform
'linux'
> process.versions
{ http_parser: '2.6.1',
  node: '5.6.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2f' }

```

Even if I force proper tokens in the 

```node
//regTokens  is an array of working tokens
sender.send(message, { registrationTokens: regTokens }, function (err, response) {
                if(err) logger.error("sender.send",err);
                else    logger.info("response",response);
            });
```

I get this error : `No RegistrationIds given!`

the DEBUG provides : 
`node-gcm No RegistrationIds given! +0ms`

On my windows envt, the scrpt is working properly : 
```node

//WINDOWS ENVT  WORKING WITH SAME SCRIPT.
{ multicast_id: 6626093842720913000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '0:1455476622783836%67c1dd7ef9fd7ecd' } ] }
```

Do you have any idea why this is not working on my Ubuntu ?

**Comment by eladnava** [comment]
You are probably using an outdated version of `node-gcm` on your Ubuntu environment, which doesn't have the `registrationTokens` key as it was added recently -- please update the package and try again.

**Comment by ronyrun** [comment]
Hello, @eladnava 
I'm so sorry, an old local version of node-gcm was installed.
