### ISSUE TITLE
IOS push through GCM is not going through

### ISSUE THREAD

**Issue by sunojvijayan** [ToothlessGear/node-gcm#220]
I have installed tha app in android and the push is going through fine. After that I have followed the tutorial here https://developers.google.com/cloud-messaging/ to generate the .plist file and added it to ios. then tried pushing but GCM returns error saying token id not registered. I am using the same code to generate gcm id and it works fine. The only difference I can see is that there is a new credential generated when i created in GCM when I followed the tutorial above and it says server key in it instead of browser which is shown in android version. Please help

**Comment by hypesystem** [comment]
There will be a separate Api key for each device. Your iOS device does not use the same as the one you used for Android, so you probably just need to use the correct api key when sending to iOS devices.

**Comment by sunojvijayan** [comment]
I have tried that too. Is that the one which is auto generated when we complete the gcm process with certificates

**Comment by sunojvijayan** [comment]
When i try using the auto generated api key it throws 401 error

**Comment by sunojvijayan** [comment]
I am getting this error

{ multicast_id: 5852817899341144000,
  success: 0,
  failure: 1,
  canonical_ids: 0,
  results: [ { error: 'InvalidRegistration' } ] }

**Comment by sunojvijayan** [comment]
There is something about a .pem file

**Comment by hypesystem** [comment]
Yes, it should be the one auto-generated when registering your iOS app for GCM.

`InvalidRegistration` means that the registration id you are trying to send to does not exist for the API key you are using.

**Comment by sunojvijayan** [comment]
I have tried another apns module but its working fine. But when sending to GCM it says invalidRegistration

**Comment by sunojvijayan** [comment]
After creating .plist file i have copied it to the project folder of ios

**Comment by hypesystem** [comment]
Have you followed the instructions for setting up [GCM on iOS](https://developers.google.com/cloud-messaging/ios/client)?

**Comment by hypesystem** [comment]
This is not a problem with the node-gcm library, but with your client implementation. You should probably consult [StackOverflow](https://stackoverflow.com) or a similar place for an answer to the specific question :-)

**Comment by Warp505** [comment]
@sunojvijayan Did you succeed ?
