### ISSUE TITLE
Unable to install this plugin, I didn't find plugin.xml file

### ISSUE THREAD

**Issue by ashwin4av** [ToothlessGear/node-gcm#222]
Hi , I am unable to install this plugin ,  please @ToothlessGear, @hypesystem and @eladnava  Help me on this issue . find the attached screen,

Thanks , 
Ashwin.  

![node-gcm_plugin_issue](https://cloud.githubusercontent.com/assets/17904195/13911467/e2dd4e6e-ef56-11e5-8d4f-0e35e73f193a.PNG)

**Comment by eladnava** [comment]
You should be installed with `npm` by running the following command in your Node.js package base directory (with `package.json`):

```npm install node-gcm --save```

**Comment by ashwin4av** [comment]
@eladnava thanks for quick response , Still i am unable to install.. PFA screen

![node-gcm-2](https://cloud.githubusercontent.com/assets/17904195/13913780/dcb6ec48-ef6f-11e5-8bfe-6b03a2ea3a7c.PNG)

**Comment by hypesystem** [comment]
The error message tells you what is wrong: `"Microsoft IT Showcase"` is an invalid name. My guess is that this is the name you have given your project in your own package.json.

**Comment by eladnava** [comment]
@hypesystem Nice catch! Indeed the `npm` error is a little bit vague, but I'm pretty sure it's due to an invalid naming convention within the `package.json`.

**Comment by eladnava** [comment]
@ashwin4av Closing the issue due to lack of response. Let us know if you still need help.
