### ISSUE TITLE
Change port from 443 to some other port

### ISSUE THREAD

**Issue by sunojvijayan** [ToothlessGear/node-gcm#223]
Hi I need to send push from a secure environment. I only have access to outside via data power. Unfortunately in the data power I am using port 443 is being used by another service. Can we change the port from with in the code to achieve this. The data power will redirect the port to 443 with the outgoing connection when hitting GCM.

Please help?

**Comment by eladnava** [comment]
@sunojvijayan This question is out of the scope of this library. I'd suggest asking on the NetworkEngineering StackExchange:
http://networkengineering.stackexchange.com/

**Comment by sunojvijayan** [comment]
What if we change the port in constants.js

**Comment by hypesystem** [comment]
I agree with @eladnava --- this is not the place for figuring this problem out. Good luck figuring it out, though!

**Comment by sunojvijayan** [comment]
Okay. Thank you guys
