### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by pcnetsoft-projects** [ToothlessGear/node-gcm#227]
I tried to solve this problem, and i have been read the other issues, but didn't slove

I got 401 error:

`var gcm = require('node-gcm');

      var message = new gcm.Message();
      message.addData('key1', 'msg1');
      var regTokens = ['MY_DEVICE_REG_ID'];
      var sender = new gcm.Sender('MY_SERVRE_API_FROM_GOOGLE');
      sender.send(message, {
        registrationTokens: regTokens
      }, function(err, response) {
        if (err) console.error('Error : ' + err);
        else console.log('response' + response);
      });`

**Comment by eladnava** [comment]
Looks like you didn't replace the GCM API key with your own key.

Check this out:
https://github.com/ToothlessGear/node-gcm/issues/151

**Comment by pcnetsoft-projects** [comment]
It's solved.

I didn't change anything, but it's need more time to be activated in Google.

**Comment by hypesystem** [comment]
Thanks for letting us know what caused the problem -- good to know if anyone encounters this in the future :smile:

**Comment by pcnetsoft-projects** [comment]
The problem is back to me, I don't know why, and i need to solve it .

You can check this example(Real API and token key)
https://tonicdev.com/5712577524d46e1200acede5/571a677d05a61111000d0e0d

**Comment by pcnetsoft-projects** [comment]
The problem is back to me, I don't know why, and i need to solve it .

You can check this example(Real API and token key)
https://tonicdev.com/5712577524d46e1200acede5/571a677d05a61111000d0e0d

**Comment by eladnava** [comment]
What kind of API key are you creating in the Google APIs Console?

Server key? Browser key?

**Comment by pcnetsoft-projects** [comment]
I used the Server Key.
I'm building APIs for my own Android application, and using Nodejs/Express for that.

**Comment by eladnava** [comment]
Please try creating and using a Browser Key without any referrer restrictions to see if the 401 error goes away.

**Comment by hypesystem** [comment]
As far as I can tell using a server key should be fine. 401 is returned directly from GCM, [which states](https://developers.google.com/cloud-messaging/http-server-ref#table4) that it is an error with authentication of the sender account. It sounds like you are either passing a wrong key (copied incorrectly, or similar).

**Comment by eladnava** [comment]
I recall having an issue when GCM was first released, during the first week, that only a browser key would work for some reason. It is definitely a shot in the dark, though.

**Comment by hypesystem** [comment]
Any news, @pcnetsoft-projects ?

**Comment by hypesystem** [comment]
Closed due to lack of response.

**Comment by pcnetsoft-projects** [comment]
Hello Team,

Sorry for the late, it was an emergency issues.
Now, It's working with me when I changed the key to 'Browser Key'.

Thanks guys.

**Comment by pcnetsoft-projects** [comment]
And I hope so that you can give me more details about the Error, not the status number only, we need a message or something like that to explain whats the error.

Good job :)

**Comment by rmehare1** [comment]
i can solve it by replace 
Browser key to server key(now using)

**Comment by atulmy** [comment]
There are two keys in https://console.firebase.google.com/project/projectId
- Server key
- Legacy server key

Got it working with **Legacy server key**

You can only **Legacy server key** _"Server key (auto created by Google Service)"_ listed in https://console.cloud.google.com/apis/credentials?project=projectId
