### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by scriby** [ToothlessGear/node-gcm#229]
Hi, I'm new to the library, and it's not clear whether I need to construct a new sender object for each message or if it can/should be reused across messages.

Thanks,

Chris

**Comment by eladnava** [comment]
Hi @scriby, and welcome to node-gcm!

You can and should reuse the sender object. 

@hypesystem, maybe we should make this more clear in the docs?

**Comment by hypesystem** [comment]
This could, indeed, be clarified :) open to suggestions.

**Comment by eladnava** [comment]
I think just adding a note above the sender declaration would be helpful within the [example usage section](https://github.com/ToothlessGear/node-gcm#example-application).

Something along the lines of:

```
// Set up the sender with your GCM API key (declare this once when sending several messages)
var sender = new gcm.Sender('YOUR_API_KEY_HERE');
```

**Comment by hypesystem** [comment]
Sure! Good idea :)

**Comment by eladnava** [comment]
@scriby would you like to submit a PR with this documentation improvement?

**Comment by scriby** [comment]
I'm on vacation until next week, but I should be able to put something together for this if I don't forget.

**Comment by eladnava** [comment]
PR submitted (#269).
