### ISSUE TITLE
How can I send Big Picture Style notification with this?

### ISSUE THREAD

**Issue by khurshid-alam** [ToothlessGear/node-gcm#247]
Is it possible to send big picture style notification with this? 

![image](http://i1.wp.com/www.feelzdroid.com/wp-content/uploads/2015/09/expand_notification_android.png?resize=264%2C300)

**Comment by eladnava** [comment]
@khurshid-alam the built-in notification support is limited to only title / body / icon and a few others:
https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json

To display an image like the one you posted, you need to dispatch your own `Notification` using the `Notification.BigPictureStyle`, passing in the image like so:
https://developer.android.com/reference/android/app/Notification.BigPictureStyle.html

You can send a link to download the image via GCM, have the device download it, read it into a `Bitmap`, and then display it using `NotificationManager`.

**Comment by govardhanraoganji** [comment]
yes @khurshid-alam, but @eladnava said was right and if you want you can do what ever you want. you need to override the Notification.

You need pass image URL as parameter in payload like body or data attributes and based on your logic Notification will display.

You need to take care about the image sizes, if it is big image notification looks ugly.
