### ISSUE TITLE
Can we use the Promise.promisify method on the sender.send function() ? 

### ISSUE THREAD

**Issue by monera23** [ToothlessGear/node-gcm#250]
I tried using Promise.promisify method of bluebird library, to get the return result as a promise. But I was getting an error while doing this `-[TypeError: this.sendNoRetry is not a function]`,
This is the code for it - 

```js
var sender = new gcm.Sender('API_KEY');
var sendergcm = Promise.promisify(sender.send);
	return sendergcm(message,{registrationTokens: regTokens})
				.then(function(response){
					console.log(response);
					return response;
				}).catch(function(err){
					console.log(err);
					return err;
				});  
```

**Comment by hypesystem** [comment]
I think this should work if you bind the sender object to the send method in the second line:

```js
var sendergcm = Promise.promisify(sender.send.bind(sender));
```

`sender.send` refers to the `send` function *without* the context of the sender --- you need to explicitly bind this context.

**Comment by monera23** [comment]
Ok thanks.
