### ISSUE TITLE
Disallow data.from in the Message payload

### ISSUE THREAD

**Issue by paul-matthews** [ToothlessGear/node-gcm#254]
On creation of FCM messages, log a warning or error for addData('from', 'xxx'); As this causes a 400 error with FCM.

**Comment by eladnava** [comment]
Hi @paul-matthews,
Can you please link to where this is documented in the FCM docs? I wasn't able to find it in the HTTP FCM App Server Protocol:
https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by hypesystem** [comment]
It doesn't say in the documentation, but I experienced this, too, at some point. I think this is a good addition, both for `master` and `v1` branches.

@paul-matthews if you're up for it, a PR would be super nice
