### ISSUE TITLE
FCM compatibility

### ISSUE THREAD

**Issue by PopTudor** [ToothlessGear/node-gcm#255]
is this compatible with the new FCM ? to me it seems there is nothing to be changed on the serverside but I might be wrong

**Comment by hypesystem** [comment]
Yes, it is :-) we have even updated the API endpoint in the latest version. We could probably add a note to the README clarifying that it does work for FCM.

**Comment by eladnava** [comment]
README has been updated to reflect support for FCM.

**Comment by atgillette** [comment]
I'm thinking about migrating from gcm to fcm.  Does anyone know if my id will stay the same?  And is there any gotchas to doing the migration?

**Comment by eladnava** [comment]
@atgillette Yes, FCM is mostly an endpoint change. The registration IDs have not changed, no gotchas as far as I know. FCM is simply a re-branding of GCM with a few more features added, while maintaining backward-compatibility.
