### ISSUE TITLE
Badge for Android

### ISSUE THREAD

**Issue by miparnisari** [ToothlessGear/node-gcm#259]
Is there a way to send a badge update for Android?

**Comment by eladnava** [comment]
Android does not have a badge icon for apps (however, some manufacturers manually add support for this -- the code to make it work is pretty hack and different for every manufacturer). You could implement the required logic in your push BroadcastReceiver after sending the badge count via GCM.

**Comment by hypesystem** [comment]
It seems this has been answered.

(I don't know anything about this :disappointed: )
