### ISSUE TITLE
Support send to multiple topics

### ISSUE THREAD

**Issue by vibgy** [ToothlessGear/node-gcm#261]
FCM has introduced a way to send notification to multiple topics using the "condition" parameter in send API. 
Ref: https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by eladnava** [comment]
@vibgy Excellent PR!

However, could it be better to introduce a brand new recipient key `condition` instead of piggybacking on the `topic` parameter? @hypesystem

**Comment by vibgy** [comment]
@eladnava Thank you. 
Let me know.. I was also debating if I should introduce "condition" or not. If you guys want me to change it, I'm happy to do so.

**Comment by hypesystem** [comment]
Cool that this has been introduced! I think we should use the "condition" parameter.

This might complicate the interface for v1 or force us to rethink some things. (See and discuss at #238)

**Comment by hypesystem** [comment]
I should clarify: let's use "condition" as it is closer to the underlyibg interface :)

Don't forget to add yourself as contributor in the package :)

**Comment by vibgy** [comment]
Sure.. I'll update the PR. Thank you @hypesystem !

**Comment by vibgy** [comment]
I updated the PR. Please review. Thanks you @hypesystem @eladnava ..

**Comment by eladnava** [comment]
PR has been merged. Thanks for your hard work!
