### ISSUE TITLE
Feature request: Promise support

### ISSUE THREAD

**Issue by dan-perron** [ToothlessGear/node-gcm#263]
Functions that take a callback should return a promise if no callback is provided.

**Comment by hypesystem** [comment]
It should be possible to promisify the exposed interface, and it will be even easier with the upcoming v1 :)

i don't think we will do this for the v0 branch, but we might consider it on the v1 branch.

Personally I think letting the user promisify the interface is the superior option, as this is easy and limits the scope of this lib. I am open to discussion on this point, though.

**Comment by dan-perron** [comment]
Is there a timeline for V1?

I'd consider creating a patch if you'd be interested in the feature (and it's going to be released in the near future)

**Comment by hypesystem** [comment]
The timeline is "when we've checked most or all things off our list" #238 -- my best guess is quite soon after my summer holiday is up. Early to mid september, probably.

**Comment by dan-perron** [comment]
Fair enough. Starting to chew on this a little bit. 

Can you explain the rationale behind using nextTick for calling callbacks in many places rather than calling them directly? 

Let me know if there's a better place to post a question like this.

**Comment by hypesystem** [comment]
A function that takes a callback should never call that callback before yielding to the event loop. Using http or fs or similar usually does this, but for consistency it may slmetimes be necessary to do this explicitly.

It is commonly expected that code like this will always print "b" before "a":

```js
something(function(error) {
    console.log("a");
});

console.log("b");
```

Calling the callback directly in the cases you refer to would result in "a" being printed before "b".

**Comment by eladnava** [comment]
This post also covers it nicely:
https://howtonode.org/understanding-process-next-tick

Consider this example taken from the post:
```js
var client = net.connect(8124, function() { 
    console.log('client connected');
    client.write('world!\r\n');
});
```

In the above case, if for some reason, net.connect() invoked the callback directly without `process.nextTick`, the callback would be called immediately, and hence the `client` variable will not be initialized when the it's accessed by the callback to write to the client!

**Comment by eladnava** [comment]
And for what it's worth, I'd love for promises to be supported out of the box in v1. I personally yield promises in generator functions in most of my projects and I hate having to promisify or thunkify them manually. I love it when libraries provide either a callback or promise interface (if a callback is omitted).

**Comment by hypesystem** [comment]
Alright :-) let's do it

**Comment by dan-perron** [comment]
For your consideration #264

**Comment by eladnava** [comment]
Closing this as PR was merged successfully. 😄
