### ISSUE TITLE
 notification banner doesn't appear

### ISSUE THREAD

**Issue by billidani7** [ToothlessGear/node-gcm#265]
I send notification to my iOS testing device using this lilbray and the notification banner doesn't appear. The app is in background. When i bring the app to foreground i can see the notification at the logs.

```
var message = new gcm.Message();
message.addNotification('body', 'World');
```

Below is the debugger output
```
{
    aps =     {
        alert = World;
    };
    "gcm.message_id" = "0:1470923226991394%1947ecfe1947ecfe";
}
```
When I try to send form firebase console , the notification appears successfully with banner at the lock screen of my phone.

**Comment by billidani7** [comment]
The problem fixed with priority: 'high'.

**Comment by hypesystem** [comment]
Great that you fixed your problem :smile:
