### ISSUE TITLE
get registrationToken for Node.js

### ISSUE THREAD

**Issue by reactivize** [ToothlessGear/node-gcm#266]
Hi,
I see the api in Java for getting the registration token(s) as....
String refreshedToken = FirebaseInstanceId.getInstance().getToken();

Would you know the api or idiom for retrieving these in Javascript?
I don't see a way on the 'firebase' npm module.
Thanks!

**Comment by hypesystem** [comment]
Hi!

You need to get the registration ID on the *client*, then somehow transmit it to your server, which runs node-gcm and sends notifications to the registration ids.

Are you writing your app in standard Android Studio (Java)? In that case, you should never want to use Javascript to get a reg id.

**Comment by nguyenlehuutai** [comment]
When you get refreshedToken. you should put token on database firebase.

**Comment by eladnava** [comment]
Closing due to lack of response. Please reopen if you still experience this issue.
