### ISSUE TITLE
Question: Error codes

### ISSUE THREAD

**Issue by m1ome** [ToothlessGear/node-gcm#272]
Hi, can anyone paste a link to all error codes?
I mean i want remove "wrong" token i have in my DB but don't see any links about error codes.
And i don't know what error codes i should resolve as "bad/invalid token" code.

Thank you.
This is a question, not a bug.

**Comment by eladnava** [comment]
Hi @m1ome,
Check out #221, it describes how to achieve what you are trying to do.

**Comment by m1ome** [comment]
@eladnava thank you!
