### ISSUE TITLE
Group notification

### ISSUE THREAD

**Issue by yesroh** [ToothlessGear/node-gcm#284]
Is there any way to group the notifications?

**Comment by eladnava** [comment]
You're probably looking for `collapse_key`.

More info here:
https://developers.google.com/cloud-messaging/http-server-ref#table1

**Comment by debjeet-sarkar** [comment]
@yesroh @eladnava  collapsible messages are really useful for send-to-sync messages when you dont really want to bug your client side with a huge bunch of messages. 

If the grouping talked about is like a single notification having all the previous downstream  messages, the corresponding handling is to be done on the Android client side using the Notification.InboxStyle and binding the PNs based on a pre-defined key.

**Comment by hypesystem** [comment]
@debjeet-sarkar I agree, this sounds like a thing that should be solved client-side. I'm going to close the issue here.

@yesroh I hope you found the comments here at least slightly helpful, and hope you find the solution :-) (But it isn't a problem that node-gcm can solve for you.) Best of luck!
