### ISSUE TITLE
sending push notification to a group of devices

### ISSUE THREAD

**Issue by nurulnabi** [ToothlessGear/node-gcm#286]
I am new to gcm. while I was looking at node-gcm I found that notificationKey is deprecated. So I want to know how I can send notification to a group of devices?

**Comment by eladnava** [comment]
Device groups in FCM are not deprecated, it's just that the parameter `notificationKey` itself is deprecated.

You should instead use the `to` parameter:

```js
sender.send(message, { to: notificatioKey }, function(err, response) {
  if(err) console.error(err);
  else    console.log(response);
});
```
