### ISSUE TITLE
multiple users on single device

### ISSUE THREAD

**Issue by nurulnabi** [ToothlessGear/node-gcm#287]
I have come across two problems as described below.

1. if user1 logs out and user2 logs in the app on the same device. Now suppose a notification for user1 is sent from the server. Will the user2 get that notification or not if yes then how can it be avoided?

2. if my andriod app tries to register multiple time on gcm, will it get different registration id or the same one?

**Comment by hypesystem** [comment]
Hi @nurulnabi ! Unfortunately these are Android client-specific questions, and this library only deals with the server-side aspect, so you are probably better off asking it on [StackOverflow](http://stackoverflow.com/) or somewhere similar! Sorry 😦 

Best of luck 😄
