### ISSUE TITLE
data field values are converted to string

### ISSUE THREAD

**Issue by varungupta85** [ToothlessGear/node-gcm#289]
I am using this package to send remote notifications to Android devices. I use the `data` field to send the notifications. I am observing that all the fields are received as strings in my app in the `GcmListenerService` even if some of the fields that I sent are integers or booleans. Is that expected?

**Comment by eladnava** [comment]
Yes, GCM/FCM stringifies your entire payload, including integers, booleans, arrays, and objects.

A workaround is to send `JSON.stringify(data)` and have your Java app parse the JSON string into an object:
http://stackoverflow.com/a/36282596/1123355
