### ISSUE TITLE
Q: notId is missed in documentation?

### ISSUE THREAD

**Issue by mikhail-riabokon** [ToothlessGear/node-gcm#293]
Hi,

First of all thank you for this package, it's really helpful. And I would like to ask you about **notId** key in **Message**. 

I am using Cordova for building Android application, and Node.js as a back-end. And the first thing which I have tried was a [usage example](https://github.com/ToothlessGear/node-gcm#usage). But than a new push notification was delivered old one was replace to a new, and I expected that it should be like a list of notifications from the same app. I found an [answer](http://stackoverflow.com/a/17160990) on my question for Android developers, but as I was using Cordova + [plugins](https://github.com/phonegap/phonegap-plugin-push), I am not allowed to change Android client code, only Message properties. And I discovered that if I pass a **notId** property to a Message data as an integer (which will be increased for each message), my notifications list will look like as expected, old notification is not replaced by a new one.

My question is, would it be possible (and correct regarding to the issue which I had) to update a documentation?

**Comment by eladnava** [comment]
Hi @mikhail-riabokon,
Thanks for the suggestion!

It appears `notId` is specific to [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads) and the way it handles the notification payload.

Since `node-gcm` is not specific to Phonegap/Cordova, I think documenting this in our project would be out-of-scope.

@hypesystem What do you think?

**Comment by mikhail-riabokon** [comment]
@eladnava Thank you for quick response. And you are right, I am using phonegap-plugin-push, but I did not find the way of configuration notId in this plugin, because as I understood, it's a part of payload which I [receive from server](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/GCMIntentService.java#L333).

**Comment by eladnava** [comment]
@mikhail-riabokon The plugin recommends simply setting the `notId` property in the `data` payload of your notification:


```js

// Prepare a message to be sent
var message = new gcm.Message({
    data: { notId: 123 }
});
```

**Comment by mikhail-riabokon** [comment]
@eladnava Thank's. I missed such info in plugin docs, because I thought that problem was on sender side. 

Anyway, thank you for node-gcm and quick answers. I do not have any questions. Should I close it?

**Comment by hypesystem** [comment]
Yeah, I think you're right @eladnava -- this belongs in phonegap-plugin-push. You did the right thing bringing this up, though, @mikhail-riabokon, so thanks for that :-) good luck with the project
