### ISSUE TITLE
i don't get any response with fake tokens on send 

### ISSUE THREAD

**Issue by siemya** [ToothlessGear/node-gcm#296]
İ have 1000 tokens, one is real and the rest is "xxxx..." i receive a notification to my phone but i dont get any response.

```
return apnConnection.send(note, token).then(result => {
  console.log(result);
  return result;
}).catch(err => {
  console.log(err);
  return err;
});
```

**Comment by eladnava** [comment]
Wrong repository. This is `node-gcm`, we do not interface with APNs.
