### ISSUE TITLE
Implement new GCM features presented at Google I/O'13

### ISSUE THREAD

**Issue by ToothlessGear** [ToothlessGear/node-gcm#30]
* upstream messaging (including user notifications)
* persistent connection
* Chrome Notifications

**Comment by hypesystem** [comment]
A pull request for user notifications has been submitted: #96.

**Comment by hypesystem** [comment]
This issue should be split into (at least) three several issues.

**Comment by hypesystem** [comment]
Upstream messaging is used for devices (clients) to communicate with other devices belonging to the same user. It is out of scope of this library (which concerns the server side). Source: http://developer.android.com/google/gcm/notifications.html

I have created a separate issue for user notifications: #107

**Comment by hypesystem** [comment]
Upstream messaging and persistent connections are intrinsically connected: https://developer.android.com/google/gcm/ccs.html#upstream

Chrome Notifications do not differ from any other notifications, and are actually already supported (although sending upstream notifications from Chrome obviously isn't).

**Comment by hypesystem** [comment]
I have split out the CCS/Upstream messaging into a separate issue, #109. With that, I can close this issue (as the parts have now been split out).
