### ISSUE TITLE
Increase badge number

### ISSUE THREAD

**Issue by Deadsoil** [ToothlessGear/node-gcm#300]
I have got it to add a badge number in IOS to the app icon, but is there a way to increase the number each time a notification is sent? 

Also, is there a way to set the badge number on android?

**Comment by eladnava** [comment]
On Android, use this:
https://github.com/leolin310148/ShortcutBadger

You cannot ask iOS to increment your badge number. Your backend needs to know how many pending notifications are waiting for the device and send that number with each latest push notification.
