### ISSUE TITLE
I sent the notification but It's not appears on Firebase Notifications

### ISSUE THREAD

**Issue by jfbaquerocelis** [ToothlessGear/node-gcm#305]
Hi, I'm trying send notifications from my server to my android app but it's not works.

This is my code:
```javascript
let sender = gcm.Sender('AIza***********************j8Yo');
let registrationTokens = ["AAAA7nujsgk:***********************************J"];
let message = new gcm.Message({
  priority : "high",
  notification: {
    title: "Hello, World",
    icon: "ic_launcher",
    body: "This is a notification that will be displayed if your app is in the background."
  },
});
sender.send(message, { registrationTokens : registrationTokens }, function (err, response) {
  if (err) console.error(err);
  else console.log(response);
});
```

The response is:
```
{ multicast_id: 7411791926489017000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '0:1503603462005768%0000000000000000' } ] }

```

But, My app is not showing the notification and on Firebase I don't see the notification in the panel.
![image](https://user-images.githubusercontent.com/6578139/29686221-c6e9d6a6-88dd-11e7-8d53-63936eadea01.png)

What is I doing wrong? Help me please :pray:

**Comment by eladnava** [comment]
Hi @jfbaquerocelis,
Is there any chance that your app is in the foreground when you are testing to see if the notification was received?

As a reminder, sending a push notification with the `notification` fields is only displayed when your app is in the background.

**Comment by eladnava** [comment]
Closing due to lack of response. Feel free to reopen if you are still experiencing this.
