### ISSUE TITLE
Push data formatting issue

### ISSUE THREAD

**Issue by zohaib055** [ToothlessGear/node-gcm#306]
i get this error on android side when send payload via node-gcm

Unterminated object at character 48 of {type=pn_comments, cause_id=22, comment=zohaib ahmad has commented on your cause}

it got resolved when i replace _ with spaces in comment string  looks like there is an issue in lib 

anyone got the same issue ?

**Comment by hypesystem** [comment]
Hi! Could I get you to share the code you use to send the payload, so we can see if it has anything to do with that?

Can you tell me exactly what the data payload looks like on the server-side when you send it?

Thanks ! :smile:

**Comment by eladnava** [comment]
Closing due to lack of response. Feel free to reopen if you are still experiencing this.
