### ISSUE TITLE
[Question] How does GCM handle expired .p12 files

### ISSUE THREAD

**Issue by bardu** [ToothlessGear/node-gcm#307]
Does someone here know how GCM handles expired .p12 files?
 
Our old one has expired and we generated a new one and uploaded to GCM (not FCM).

However, when running our cordova based app with the cordova push plugin push notifications are not delivered to iPhones anymore.

In Xcode console we see:
`LocalIsSmart[713:743786] libMobileGestalt MobileGestaltSupport.m:153: pid 713 (LocalIsSmart) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-09-17 18:10:29.078057-0700 LocalIsSmart[713:743786] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)`

Any clarification would be much appreciated.

**Comment by hypesystem** [comment]
Hey @bardu.

I'm not really sure about this. I think the appropriate place to ask a question like this would be [StackOverflow](https://stackoverflow.com/), as it isn't directly related to the library we provide (to interact with the FCM service), but to how the FCM service itselfs behaves.

Sorry I couldn't be of more help :-( 

Let us know if you find out!
