### ISSUE TITLE
Unable to send notification on multiple topics (more than 5)

### ISSUE THREAD

**Issue by djvickx** [ToothlessGear/node-gcm#326]
Hello, 
I am using firebase condition to send notification on multiple topics. It works like charm for upto 5 topics but I need to send on more than 5 topics. Please guide how I can do that.
Following is the code:

```
condition = "'TopicA' in topics || 'TopicB' in topics || 'TopicC' in topics || 'TopicD' in topics || 'TopicE' in topics || 'TopicF' in topics || 'TopicG' in topics "
string serverKey = //SERVER_KEY

WebRequest tRequest = WebRequest.Create("https://fcm.googleapis.com/fcm/send");
tRequest.Method = "post";
tRequest.ContentType = "application/json";
var objNotification = new
{
condition = condition,
priority = "high",
data = //NOTIFICATION DATA
};
WebResponse tResponse = tRequest.GetResponse();

```

**Comment by hypesystem** [comment]
Great, thank you for moving this to a separate issue.

I can see here that you are not using our library for sending notifications via FCM in Node.js. In fact, I'm not quite sure which programming language you are using at all. It looks like C#?

The proper way of using more conditions, I think, would be splitting the topics, and sending multiple requests to FCM.

If you are not using our library, I'm afraid we can't help much, and [StackOverflow](https://stackoverflow.com/) or [AskQuestions.Tech](https://www.askquestions.tech/) would be more appropriate channels to look for answers in.

**Comment by djvickx** [comment]
Thanks for the reply @hypesystem 
I am using Google Firebase APIs to send notifications. And yes its C#. I can't send multiple requests by splitting topics as it will result in duplicate notifications to users who have subscribed to all topics. 
Can u please guide if I use FCM in node.js then I can send notification to multiple topics without splitting the topics?

Thanks,
Waqas

**Comment by hypesystem** [comment]
Ah! I see the issue... I'm not sure I have a good solution for this, I'm afraid 😦
