### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by PabloSzx** [ToothlessGear/node-gcm#334]
There are 2 broken links in the documentation at #Requirements.

You need to generate an API Key.
https://developers.google.com/cloud-messaging/gcm#apikey

If you are new to GCM you should probably look into the documentation.
https://developers.google.com/cloud-messaging/gcm.

It would be nice to have the firebase cloud messaging equivalent for "the generate an API Key"

**Comment by eladnava** [comment]
Thanks @PabloSzx, I have updated all broken links in 8256971.
