### ISSUE TITLE
`data` type appears wrong

### ISSUE THREAD

**Issue by rex-remind101** [ToothlessGear/node-gcm#338]
type for `data` is `{ [key: string]: string }`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9fd18b7cf75676be256b04e754377cbd98663a2b/types/node-gcm/index.d.ts#L33

yet examples show something closer to `{ [key: string]: string | number | boolean | undefined }`
https://github.com/ToothlessGear/node-gcm#usage

Please fix the type so casting isn't required.

**Comment by eladnava** [comment]
Hi @rex-remind101,
Thanks for the report. However, this needs to be changed in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). 

Would you mind opening a PR there on the `DefinitelyTyped/types/node-gcm/index.d.ts` file, with the changes you proposed?
