### ISSUE TITLE
How to add analytics label to message?

### ISSUE THREAD

**Issue by gpkamp** [ToothlessGear/node-gcm#340]
My push notifications are being sent ok but not appearing in the Firebase Cloud Messaging logs.
Their documentation mentions that you should add an analytics label.
https://firebase.google.com/docs/cloud-messaging/understand-delivery?authuser=0#adding_analytics_labels_to_messages
How do I do this with node-gcm?

**Comment by eladnava** [comment]
Hi @gpkamp,
As per the [FCM docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages?authuser=0#androidfcmoptions), set the `fcm_options. analytics_label` object using the following code:
```
var gcm = require('node-gcm');

// Set up the sender with your GCM/FCM API key (declare this once for multiple messages)
var sender = new gcm.Sender('YOUR_API_KEY_HERE');

// Prepare a message to be sent
var message = new gcm.Message({
    data: { key1: 'msg1' },
    fcm_options: {
        analytics_label: 'call-notification'
    }
});

// Specify which registration IDs to deliver the message to
var regTokens = ['YOUR_REG_TOKEN_HERE'];

// Actually send the message
sender.send(message, { registrationTokens: regTokens }, function (err, response) {
	if (err) console.error(err);
	else console.log(response);
});
```

**Comment by ltnilaysahu** [comment]
**I tried with 1.0.3 , it didnt work**
var gcm = require('node-gcm');
 
// Set up the sender with your GCM/FCM API key (declare this once for multiple messages)
var sender = new gcm.Sender('.....');
 
// Prepare a message to be sent
var message = new gcm.Message({
     notification: {
        title: 'Title of your push notification', 
        body: 'Body of your push notification' 
    },
  data: { key1: 'msg1' },
    fcm_options: {
        analytics_label: 'call-notification'
    }
});
 
// Specify which registration IDs to deliver the message to
var regTokens = ['.....'];
 
// Actually send the message
sender.send(message, { registrationTokens: regTokens }, function (err, response) {
    if (err) console.error(err);
    else console.log(response);
});

**Comment by eladnava** [comment]
Hi @ltnilaysahu,
When debugging `node-gcm`, I could confirm that using your exact sample code, the `fcm_options.analytics_label` is passed in the request to the FCM API:

![Screen Shot 2020-07-24 at 10 59 59 AM](https://user-images.githubusercontent.com/4394189/88411044-e0e64100-cd9c-11ea-9b11-dba4024ce8cb.png)

Therefore, there is no bug in `node-gcm`. Instead, check for a delay in the analytics being posted to the Firebase dashboard, or using the wrong label ID.

**Comment by eladnava** [comment]
Hi @ltnilaysahu,
Nice catch. Indeed this parameter is not supported in the FCM Legacy HTTP Server API.

Currently, `node-gcm` is specifically built to support the legacy API format and there are no current plans to migrate to the FCM HTTP v1 API. 

I'd recommend checking out the official [firebase](http://npmjs.com/package/firebase) package to send notifications.

You can then add an analytics label by setting the `fcm_options.analytics_label` field in the `message` object:
https://firebase.google.com/docs/cloud-messaging/send-message
