### ISSUE TITLE
fcm_options and analytics_label fields are not sent to FCM servers?

### ISSUE THREAD

**Issue by ltnilaysahu** [ToothlessGear/node-gcm#346]
i tried `firebase-admin` npm package with this `{
  notification: {
        title: 'Title of your push notification', 
        body: 'Body of your push notification' 
    },
  data: {score: '850', time: '2:45'},
  tokens: registrationTokens,
  fcmOptions: {analyticsLabel: 'hello3'},
}
` . Observe  `analyticsLabel` this parameter is used for firebase events, it worked. But when i tried passing via node-gcm it was not transferred to firebase

**Comment by ltnilaysahu** [comment]
i tried passing `fcm_options: {analytics_label: 'hello3'},` this as well. didn't work

**Comment by eladnava** [comment]
Hi @ltnilaysahu,
Please use this exact code which is confirmed to work:
https://github.com/ToothlessGear/node-gcm/issues/340#issuecomment-630349825
