### ISSUE TITLE
Add snyk to fix vulnerabilities faster

### ISSUE THREAD

**Issue by mtrezza** [ToothlessGear/node-gcm#354]
Add snyk to this repository to auto-create PRs to fix vulnerabilities instead of waiting for someone to open a manual PR.

**Comment by mtrezza** [comment]
@eladnava @ToothlessGear What do you think?

**Comment by ToothlessGear** [comment]
@mtrezza I'm open to give maintainer privileges to you, however maybe @eladnava and @hypesystem have some input too.

**Comment by mtrezza** [comment]
@ToothlessGear Thanks, I'll be happy to hear any input and obviously we would discuss any suggested changes to find the best way forward for the repo.

**Comment by eladnava** [comment]
@mtrezza @ToothlessGear I think it would be great to have automated vulnerability fix PRs. I'm more inclined to use GitHub's built-in [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies), however only the repo owner (@ToothlessGear) can enable it, by visiting this page:
https://github.com/ToothlessGear/node-gcm/network/updates

Dependabot works similarly to Snyk by constantly scanning the project dependencies and alerting when a vulnerability is detected, and opening a PR with a fix if possible to do so in an automated way.

**Comment by eladnava** [comment]
@mtrezza Sounds good, in both cases @ToothlessGear will need to set these up. Here are instructions for each one:

1) [Snyk](https://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration)
2) [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies)

**Comment by mtrezza** [comment]
@ToothlessGear How should we proceed with this?

**Comment by ToothlessGear** [comment]
@mtrezza: I think I've set everything up now. 
Regardless, I also gave you  Collaborator rights on the repo, as well as npm.

**Comment by mtrezza** [comment]
Thanks! I'll take a look soon.

**Comment by PeterBurner** [comment]
Any news?

**Comment by mtrezza** [comment]
It seems this has been addressed. I noticed Snyk just opened a PR.

**Comment by mtrezza** [comment]
@ToothlessGear I've requested org access on Snky to set this up, you may have received an email.

**Comment by ToothlessGear** [comment]
@mtrezza Should be approved now.

**Comment by mtrezza** [comment]
It's strange that Snky doesn't seem to have opened even a single PR since it was added.

**Comment by mtrezza** [comment]
Snky is opening PRs, closing this.
