### ISSUE TITLE
didReceiveRemoteNotification:fetchCompletionHandler not called.

### ISSUE THREAD

**Issue by RoyDeng** [ToothlessGear/node-gcm#357]
I set contentAvailable to true, but it didn't work.

```
message = new gcm.Message({
    priority: 'high',
    contentAvailable: true,
    data: {
        notification_type: 1,
        ...
    },
    notification: {
        title: '測試',
        body: '測試',
        sound: 'default'
    }
});
```

**Comment by eladnava** [comment]
Hi @RoyDeng,
1) iOS Silent Notifications require the Background Modes -> **Remote Notifications** capability to be enabled. Pleas ensure this capability is enabled in your Xcode project settings, and try sending a silent notification with `contentAvailable: true` again.

2) Please ensure your app has not been swiped away (killed) as this will prevent silent notifications from waking up your app (this is an Apple iOS platform restriction).

3) If testing using the Xcode debugger, please note that the debugger won't break on `didReceiveRemoteNotification:fetchCompletionHandler` if your app is not in foreground when a silent notification comes in.

**Comment by RoyDeng** [comment]
Thanks for your response.
I would like to confirm that this setting is equivalent to `content-available: 1`?

**Comment by eladnava** [comment]
Hi @RoyDeng,
Yes, setting `contentAvailable: true` will lead to `content-available: 1` being passed to the APNs server and a silent notification being sent.

Please confirm items 2 and 3 are not the cause as well (app not killed/not being debugged in background).

**Comment by RoyDeng** [comment]
I have solved the problem, thanks.

**Comment by eladnava** [comment]
@RoyDeng please let us know what the underlying cause of the problem was
and how you fixed it as it may help other developers in the future facing
the same issue.

**Comment by RoyDeng** [comment]
Hi, I found that I also use didReceive and didReceiveRemoteNotification at the same time. Based on the life cycle, it does not call the function I expect.
