### ISSUE TITLE
Handle non-HTTP errors

### ISSUE THREAD

**Issue by silentjohnny** [ToothlessGear/node-gcm#375]
When a non-HTTP error occurs, e.g., a timeout, the `err` instance does not contain a `response`.

This means that this:
```
const { response: res } = err;

if (res.status === 401) {
```

will fail because of `res` being `undefined`

**Comment by eladnava** [comment]
Thanks for catching this and submitting a PR @silentjohnny!

Merged and published to `npm` as `1.1.1`. 🎉
