### ISSUE TITLE
server gets into weird state where always returns null error and result and gcm not sent

### ISSUE THREAD

**Issue by 2fours** [ToothlessGear/node-gcm#44]
Using 0.99. The server somehow gets into a weird state where all requests return null error and result and no GCM messages are sent. Not sure why. One of my servers was running fine for over a week with no issues then this started happening today.

**Comment by hypesystem** [comment]
This might have happened if *some* messages (but not all) failed to send. This was fixed recently, in 0.9.15 (see [changelog](https://github.com/ToothlessGear/node-gcm/blob/master/README.md#changelog))

Please check if you can reconfirm :)
