### ISSUE TITLE
send method returns 'null' result

### ISSUE THREAD

**Issue by lokeshwebmobi** [ToothlessGear/node-gcm#63]
Hi,
	var message = new gcm.Message();
	var sender = new gcm.Sender('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
	var registrationIds = [];
	 
	message.addData('title','My Game');
	message.addData('message','Your turn!!!!');
	message.addData('msgcnt','1');
	message.collapseKey = 'demo';
	message.delayWhileIdle = true;
	message.timeToLive = 3;
	 

	registrationIds.push('yyyyyyyyyyyyyyyyyyy');
	 
	sender.send(message, registrationIds, 4, function (result) {
	    console.log('result',result); //return null
	});
may i know where i made mistake?

**Comment by hypesystem** [comment]
@nvcken yes, the request is too large ([413 Request Entity Too Large](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.14)). Split the list of registration ids and send several requests.
