### ISSUE TITLE
Message send success but not receiving it on test device

### ISSUE THREAD

**Issue by ilyakar** [ToothlessGear/node-gcm#66]
Hi. What is going wrong? Everything seems fine on the server but my device is not receiving anything...

sending google push notification
registrationIds: [ 'xxxxxxxx' ]
result of sending the notification to google: { multicast_id: 6735210410419146000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '0:1416737849360343%da56e82a002efde3' } ] }

**Comment by hypesystem** [comment]
This seems to be the same as #70

**Comment by hypesystem** [comment]
Closing as duplicate because I have gotten no response :)

**Comment by KhuloodAlalwi** [comment]
i have the same problem

**Comment by hypesystem** [comment]
@KhuloodAlalwi the same as in #70 or is it different?
