### ISSUE TITLE
How to wrap "message" content become multi-line if too long

### ISSUE THREAD

**Issue by nvcken** [ToothlessGear/node-gcm#68]

**Comment by hypesystem** [comment]
Please provide more detail. What are you actually asking? An example would be helpful.

**Comment by hypesystem** [comment]
This seems to be a question about displaying information on Android, and not relevant to the sending of data.

**Comment by nvcken** [comment]
@hypesystem 
srry for my late reply because busy.
I attach screeshot to make my question clean
![screenshot_2015-01-28-09-38-45](https://cloud.githubusercontent.com/assets/3489866/5937296/6b558142-a720-11e4-9dc7-11f2c1892395.jpg)

**Comment by hypesystem** [comment]
This is an Android problem, and relates to how you display the payload you send. It is not related to this library.
