### ISSUE TITLE
Deprecate `addData*`

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#88]
Deprecate `Message#addDataWithObject` and `Message#addDataWithKeyValue`.

Both of these are now covered by `Message#addData` (and will be removed in [v1](https://github.com/ToothlessGear/node-gcm/milestones/v1)).

They should probably print something to `console.warn` or something.

**Comment by ToothlessGear** [comment]
Additionally I'd suggest to write in the README that those are deprecated, or remove them entirely to avoid more confusion as I've read in the other issue #70

**Comment by hypesystem** [comment]
Added it to the changelog. Seeing as they aren't referenced anywhere else in the README, I think we are safe :)
