### ISSUE TITLE
Send to a lot of users (more than 100000)

### ISSUE THREAD

**Issue by ghominejad** [ToothlessGear/node-gcm#91]
I need to send some important news to more than 100000 Registrations ID's. why do i need to keep 100000 Ids? Is there a better solution?

**Comment by hypesystem** [comment]
You currently need to manually split your registration ids into chunks of at most 1000 before sending them. Other people have had this issue, too (#82), and a solution has been staged: #83.

You are very welcome to fork and contribute code that may solve this problem.
