### ISSUE TITLE
Full API documentation

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#98]
An interface-by-interface documentation of how to use the code would be most useful.

**Comment by dhcar** [comment]
+1. The gcm message keys have me confused.

**Comment by hypesystem** [comment]
Many of the keys are the exact equivalents of the ones specified by GCM. They are most likely explained in the [GCM HTTP documentation](https://developer.android.com/google/gcm/http.html#request). Of course, they should be mentioned in the API documentation, too.

**Comment by hypesystem** [comment]
[Docco](http://jashkenas.github.io/docco/) could be used for this purpose. I think [jasmine does this to great effect](http://jasmine.github.io/2.1/introduction.html).

**Comment by ToothlessGear** [comment]
:+1:

**Comment by hypesystem** [comment]
Fixed in #111
